Add bounding box query
openearthplatforminitiative/deforestation-api pull request #6
Opened 2023-11-28 14:45 UTC by A-Stangeland

When testing the bbox query I found that some of the geometries in the basin data are MultiPolygons. I didn't notice this before because the vast majority of the basin geometries are Polygons. I therefore added Multpolygon as a possible type for the geometry field in the pydantic response model.

2023-12-04 11:40 UTC, giltinde requested changes

2023-12-04 11:40 UTC, giltinde commented on deforestation_api/dependencies/queryparams.py
>      return start_year, end_year
Could possibly add a check to verify that `start_year <= end_year`

2023-12-04 11:40 UTC, giltinde commented on deforestation_api/dependencies/queryparams.py
> +        return lon, lat
Maybe include in the documentation that if both a point and a bbox are provided that the bbox is ignored, or enforce that only a point or a bbox can be provided (using an error)

2023-12-04 11:40 UTC, giltinde commented on deforestation_api/dependencies/queryparams.py
> +        return bbox
Alternatively you could write `if None not in bbox:`

2023-12-04 14:08 UTC, A-Stangeland commented on deforestation_api/dependencies/queryparams.py
> +        return lon, lat
I added an error if both are included.

2023-12-04 14:37 UTC, giltinde approved these changes
Nice 🤝

2023-12-05 12:48 UTC, dymbe approved these changes

2023-12-05 13:05 UTC, merged